name: Deploy Laravel to CapRover

on:
  push:
    branches:
      - main  # Change to 'master' or another branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Deploy to CapRover
        run: |
          caprover deploy \
            --caprover-url ${{ secrets.CAPROVER_URL }} \
            --caprover-password ${{ secrets.CAPROVER_PASSWORD }} \
            --caprover-app ${{ secrets.CAPROVER_APP }}
