name: Build, Push, and Deploy Laravel App to Docker Hub and CapRover

on:
  push:
    branches:
      - main  # Trigger this action when you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Runs on an Ubuntu machine

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/easyauction:${{ github.sha }} .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/easyauction:${{ github.sha }}

      # Step 6: Install CapRover CLI
      - name: Install CapRover CLI
        run: npm install -g caprover

      # Step 7: Log in to CapRover using the provided credentials
      - name: Log in to CapRover
        run: caprover login --server ${{ secrets.CAPROVER_SERVER }} --token ${{ secrets.APP_TOKEN }}

      # Step 8: Deploy the Docker image to CapRover
      - name: Deploy to CapRover
        run: |
          caprover deploy --appName ${{ secrets.APP_NAME }} --imageName ${{ secrets.DOCKER_USERNAME }}/easyauction:${{ github.sha }} --noCache
